### ISSUE TITLE
Automatic updating 15 commits behind

### ISSUE THREAD

**Issue by SkyNinja** [XboxChaos/Assembly#316] opened 2020-10-24 20:13 UTC
**Describe the bug**
The latest version of Assembly (experimental), according to Assembly, is commit [e449a6584a8e4c15854726bc0f2ae7833116afd0](https://github.com/XboxChaos/Assembly/commit/e449a6584a8e4c15854726bc0f2ae7833116afd0), as opposed to being up to date with the dev branch, as the description in settings states.

**Expected behavior**
Updates available matching the current version on Github.

**Screenshots**
![2020-10-24](https://user-images.githubusercontent.com/4765557/97092652-4e5b7500-160b-11eb-8a5c-45f362f28673.png)

**PC (please complete the following information):**
 - OS: Windows 10 Pro 1903

**Comment by ThunderWaffle** [comment] 2020-10-24 20:26
Duplicate of #226

**Closed by ThunderWaffle** 2020-10-24 20:26 UTC
